CREATE TABLE IF NOT EXISTS clients (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL CHECK (type IN ('company','lead')),
  company_name TEXT,
  full_name TEXT NOT NULL,
  phone1 TEXT NOT NULL UNIQUE,
  phone2 TEXT,
  city_id INTEGER,
  source_id INTEGER,
  sphere_id INTEGER,
  comment TEXT,
  tg_group_link TEXT,
  company_id INTEGER,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_by INTEGER,
  created_at INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER)),
  updated_at INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER)),
  deleted_at INTEGER,
  deleted_by INTEGER,
  FOREIGN KEY (city_id) REFERENCES dict_cities(id),
  FOREIGN KEY (source_id) REFERENCES dict_sources(id),
  FOREIGN KEY (sphere_id) REFERENCES dict_spheres(id),
  FOREIGN KEY (company_id) REFERENCES clients(id),
  FOREIGN KEY (created_by) REFERENCES users(id),
  FOREIGN KEY (deleted_by) REFERENCES users(id)
);
